### ISSUE TITLE
html in error messages displayed

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-sniffer#107]
![image](https://user-images.githubusercontent.com/11907254/53613982-1980eb80-3ba6-11e9-8da2-0fe58354484d.png)

**Comment by dingo-d** [comment]
Probably a parsing error, good catch. If you can provide a theme that generated that, that would be great 🙂

**Comment by timelsass** [comment]
here's twentyninteen the example code from https://developer.wordpress.org/reference/functions/add_menu_page/ added for testing: [twentynineteen.zip](https://github.com/WPTRT/theme-sniffer/files/2921698/twentynineteen.zip)

**Comment by timelsass** [comment]
It looks like that change would introduce another issue of loading unwanted iframe content:
![image](https://user-images.githubusercontent.com/11907254/53683388-344e7f80-3cce-11e9-9969-8a0ce5a4bcc5.png)

**Comment by timelsass** [comment]
added https://github.com/WPTRT/theme-sniffer/pull/113/commits/a7b6ae11ea314d2d88cb1f71a42b54e831a6cd9d to check for iframe before output

**Comment by dingo-d** [comment]
I guess there was a reason after all for futting `.text()` instead of `.html()` after all :D

**Comment by dingo-d** [comment]
Merged the PR and it works :+1: Thanks!

**Comment by DannyCooper** [comment]
I'm seeing something similar to this, the authors code isn't great but still...

![image](https://user-images.githubusercontent.com/152804/53880674-7eef3500-4009-11e9-8188-7101e13c14f2.png)

![image](https://user-images.githubusercontent.com/152804/53880680-83b3e900-4009-11e9-98c2-adb3f1d15729.png)

**Comment by timelsass** [comment]
Ah, yeah that makes sense - I'll have to take a look at what all the messages are actually outputting to come up with a solution.  I didn't give thought to if/when HTML is being output from other sniffs.  I'm not sure why that one message includes HTML around the function either since the rest don't seem to do that.

**Comment by dingo-d** [comment]
Maybe we could strip tags before outputting the message?

**Comment by joyously** [comment]
So it's just that the messaging to the user is sometimes wanting HTML and most times should show HTML?
At the point of output, the code doesn't know what's in the message. I don't think it should be escaping there. This is a case where late escaping hurts. The individual messages should be escaped where needed, since that's the point the code knows it's needed or not. The user should see the actual code that was in error, so it should not be stripped. And if there needs to be something in bold, that should be available also.

**Comment by dingo-d** [comment]
Stripped in the theme sniffer 🙂 so that we don't have html in the output. I should have been more precise

**Comment by joyously** [comment]
That was my point: sometimes it is correct to have HTML in the output. The message should not be stripped since it can contain HTML that is part of the message. If you strip the HTML out, the message doesn't convey the correct thing. 

I think the fix that already went in for this was the wrong fix. The fix should have been to remove the `<strong>` tags from that one message, because the more common case is that messages need to contain exact code from the theme accurately report the problem.

**Comment by timelsass** [comment]
yes I agree with @joyously - especially given that no other messages really appear to be wrapping things in HTML - that one should definitely follow suit.   Sent over PR for WPThemeReview

**Comment by dingo-d** [comment]
This has been fixed?

**Comment by timelsass** [comment]
the upstream has been for that message - I was using some HTML for some things in the license check messages though.  Since we control the output of the messages we create, I think we can look at `messages.message.source` to verify it's our message, and then enable using html for the ones we have control over.
