### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by STV11C** [WPTRT/theme-sniffer#169]
Hi, I just downloaded latest version from here and received following error on plugin activation. Any idea? Cheers

```
Plugin could not be activated because it triggered a fatal error.
Fatal error: Uncaught Error: Class 'Theme_Sniffer\Core\Plugin_Factory' not found in /var/www/html/wp-content/plugins/theme-sniffer-development/theme-sniffer.php:58 Stack trace: #0 /var/www/html/wp-admin/includes/plugin.php(2141): include() #1 /var/www/html/wp-admin/plugins.php(175): plugin_sandbox_scrape('theme-sniffer-d...') #2 {main} thrown in /var/www/html/wp-content/plugins/theme-sniffer-development/theme-sniffer.php on line 58
```

**Comment by dingo-d** [comment]
If you downloaded the git repository it won't work because you need to run the composer and npm and run the install scripts as described here: https://github.com/WPTRT/theme-sniffer#for-theme-sniffer-development

The best way is to download the official plugin from the wordpress.org, as that doesn't have any such issues, this is mostly used for development.

We'll have a new release out very soon 🙂

**Comment by STV11C** [comment]
Thanks for the reply and yes I downloaded from here. Will grab it from the wordpress site. Cheers.
