### ISSUE TITLE
Replace Ajax with REST API or pure PHP ajax request

### ISSUE THREAD

**Issue by grappler** [WPTRT/theme-sniffer#63]
As ajax is soooo slow it would be better to use the REST API or use a pure PHP solution for the Ajax request as WordPress is not needed while running the checks.

Here is an example how it could be done with pure PHP: https://gist.github.com/gmazzap/be3d8723f2481a7bc3bea05976544f25

**Comment by dingo-d** [comment]
So that would mean separating current `wp_ajax_` hooked functions to their own files and calling them instead of using the `admin-ajax` wrapper?

**Comment by joyously** [comment]
>  or use a pure PHP solution for the Ajax request as WordPress is not needed while running the checks.

Does that mean WordPress functions _can't_ be used? Such as `get_theme()` to see if it's a child? Or to use transients?

**Comment by dingo-d** [comment]
@joyously Ulrich was talking about the ns-theme-check plugin, not the sniffs ;)

**Comment by grappler** [comment]
> Does that mean WordPress functions can't be used? Such as get_theme() to see if it's a child? Or to use transients?

In the latest version of the plugin we run the checks on each file via AJAX. I was talking about that process and not stopping theme authors from using WordPress functions. I hope that makes sense.

> So that would mean separating current wp_ajax_ hooked functions to their own files and calling them instead of using the admin-ajax wrapper?

Yes, loading WordPress every time to run pure PHP does not make sense.

**Comment by dingo-d** [comment]
I'll take look for this tomorrow probably. And I definitely agree that we don't need to load WP every time we do the check.

**Comment by joyously** [comment]
> ns-theme-check plugin, not the sniffs
> not stopping theme authors from using WordPress functions.

One is saying it's not the sniffs, and the other is saying it's not theme author code.
I'm saying you are referring to the plugin (that runs under WordPress), checking theme author code using sniffs, so I wanted to make sure that the sniff code could still make WordPress calls to check some things such as `get_theme()` or perhaps a transient to help in sniff code.

**Comment by grappler** [comment]
> I wanted to make sure that the sniff code could still make WordPress calls

I don't expect the PHPCS sniffs to start using WordPress functions. PHPCS needs to be able to run without needing to install WordPress or a database. If the sniff needs extra information then we can pass that information along in form of arguments.

**Comment by dingo-d** [comment]
I was thinking, and could we use [fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) instead of AJAX? This gives us a bit more control over the result, as the fetch returns a promise. I think that would also give us better control over any possible errors that might come up while sniffing files (especially large JS files that can cause memory issues).

We could create a custom endpoint with the two files we now use for AJAX and then just fetch them.

I started working on rewriting this using PHP ajax, but got some other projects that came along so I kinda neglected this, but I think I will have some more time after WordCamp Zagreb.
